# Exclude files from Jekyll build
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock

# Installed gems
plugins: 
    - jekyll-target-blank
    - jekyll-redirect-from

# Gem settings

# Site settings
encoding: utf-8
lang: en-GB
title: "ACTG Lab"
logo: "/assets/img/logo.png"
description: ""
baseurl: ""
url: "https://atcglab.github.io"
repo: "https://github.atcglab/atcglab.github.io"
email: "faruqslab@gmail.com"
twitter_username: ATCG_Official
google_analytics: UA-92956541-1
css_inline: false 
markdown: kramdown
auto_ids: false
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true 

# Favicons 
favicons: 
    16: '/assets/img/logos/logo_hex@16px.png'
    32: '/assets/img/logos/logo_hex@32px.png'
    64: '/assets/img/logos/logo_hex@64px.png'
    128: '/assets/img/logos/logo_hex@128px.png'
    256: '/assets/img/logos/logo_hex@256px.png'
    512: '/assets/img/logos/logo_hex@512px.png'
    1024: '/assets/img/logos/logo_hex@1024px.png'

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /Blog.html
- title: COVID-19
  url: /COVID-19.html
- title: Team
  url: /team.html
- title: Get involved
  url: /involve.html
- title: Links
  url: /links.html
- title: Contact
  url: /contact.html

# Define collections
collections:
    Blog:
        output: true
        permalink: /BLog/:path/
    COVID-19:
        output: true
        permalink: /COVID-19/:path/
    DL:
        output: true
        permalink: /DL/:path/
    posts:
        output: true
        permalink: /posts/:path/
